version: '3.3'

volumes:
  pg_service:

services:
  pg_db:
    container_name: pg_database
    image: postgres:12.8-alpine
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_service:/var/lib/postgresql/data
    ports:
      - "1232:5432"